version: '3.8'

services:
  db:
    build:
      context: ./database
    image: shopdb:latest
    container_name: shop_postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    volumes:
      - shopdbdata:/var/lib/postgresql/data
    restart: always

volumes:
  shopdbdata:
